/* Generated by Together */

package impl.miw.business.projectmanager;

import impl.miw.presentation.postproject.PostProjectAction;

import java.util.Vector;

import com.miw.business.ProjectManagerService;
import com.miw.infrastructure.log.LogService;
import com.miw.model.Project;
import com.miw.persistence.ProjectDataService;

public class ProjectManager implements ProjectManagerService {

	private ProjectDataService projectDataService;
	private LogService log;

	public LogService getLog() {
		return log;
	}

	public void setLog(LogService log) {
		this.log = log;
	}

	public ProjectDataService getProjectDataService() {
		return projectDataService;
	}

	public void setProjectDataService(ProjectDataService projectDataService) {
		this.projectDataService = projectDataService;
	}

	@Override
	public Vector<Project> getProjects() throws Exception {
		log.debug("Entrando en getProjects");
		Vector<Project> projects = projectDataService.getProjects();
		return projects;
	}

	@Override
	public String setProjects(PostProjectAction postProjectAction)
			throws Exception {
		log.debug("Entrando en setProjects");

		Project p = new Project();
		p = postProjectAction.getModel();

		Double coste = p.getCoste();
		Double porcentaje = p.getPorcentaje();
		int users = (int) ((coste - (((coste / 100) * porcentaje))) / 100);
		p.setUsers(users);

		String status = projectDataService.setProjects(p);
		return status;
	}
}
