/* Generated by Together */

package impl.miw.business.usermanager;

import impl.miw.presentation.register.RegisterAction;

import java.util.Vector;

import com.miw.business.UserManagerService;
import com.miw.infrastructure.log.LogService;
import com.miw.model.User;
import com.miw.persistence.UserDataService;

public class UserManager implements UserManagerService {

	private UserDataService userDataService;
	private LogService log;

	public LogService getLog() {
		return log;
	}

	public void setLog(LogService log) {
		this.log = log;
	}

	public UserDataService getUserDataService() {
		return userDataService;
	}

	public void setUserDataService(UserDataService userDataService) {
		this.userDataService = userDataService;
	}

	@Override
	public Vector<User> getUsers() throws Exception {
		log.debug("Entrando en getUsers");
		Vector<User> users = userDataService.getUsers();
		return users;
	}

	@Override
	public String setUser(RegisterAction registerAction) throws Exception {
		log.debug("Entrando en setUser");
		String status = userDataService.setUser(registerAction);
		return status;
	}
}
